---

- name: "Create a layercake config directory"
  ansible.builtin.file:
    path: /etc/layercake
    state: directory
    mode: '0755'

- name: "Install podman packages"
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: "Include server tasks"
  include_tasks: server.yaml
  when:
   - enable_layercake_server

- name: "Include client tasks"
  include_tasks: client.yaml
  when:
   - enable_layercake_client
