---
- name: "Install user environment packages"
  dnf:
    name:
     - "ohpc-base"
     - "glibc-devel"
     - "gnu9-compilers-ohpc"
     - "openmpi4-gnu9-ohpc"
     - "lmod-defaults-gnu9-openmpi4-ohpc"
    state: present

- name: "Install openmpi mca config variables"
  copy:
    src: openmpimca.sh
    dest: /etc/profile.d/openmpimca.sh
    owner: root
    group: root
    mode: 0644
