---
network_config:
  interfaces:
    eth1:
      fqdn: fe{{ fe_node_number }}
      network: cvlan
      ipv6_address: "{{ global_network_config['networks']['cvlan']['ipv6_network'] | ansible.utils.nthhost(global_network_config['networks']['cvlan']['fe_offset'] + fe_node_number) }}"
      prefix_bits: "{{ global_network_config['networks']['cvlan']['prefix_bits'] }}"
