---
global_network_config:
  networks:
    cvlan:
      #network: 192.168.56.0/24
      ipv6_network: fd10:84f5:fa50::/64
      prefix_bits: 64
      netmask: 255.255.248.0  # FIXME: this isn't used
      fe_offset: 2
      compute_offset: 100
