ssh_known_hosts:
 - host: "head"
   aliases:
     - "192.168.56.2"
 - host: "fe1"
   aliases:
    - "192.168.56.3"
 - host: "node01"
   aliases:
    - "192.168.56.101"
 - host: "node02"
   aliases:
    - "192.168.56.102"
 - host: "node03"
   aliases:
    - "192.168.56.103"
 - host: "node04"
   aliases:
    - "192.168.56.104"
