---
network_config:
  interfaces:
    eth1:
      fqdn: head
      network: cvlan
      ipv6_address: "{{ global_network_config['networks']['cvlan']['ipv6_network'] | ansible.utils.nthhost(2) }}"
      prefix_bits: "{{ global_network_config['networks']['cvlan']['prefix_bits'] }}"
