---
- name: "Install podman packages"
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: "Set the mountain timezone"
  timezone:
    name: America/Denver

- name: "Install the python3-libsemanage package"
  dnf:
    name: python3-libsemanage
    state: present

- name: "Disable selinux"
  selinux:
    state: "disabled"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install the git package"
  dnf:
    name: "git"
    state: present

# FIXME: the IP address below should come from the head node's hostvars
- name: Add head node aliases to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars["head"]["netconfig"]["cvlan"]["ipv4_address"] }}    head slurm
      {{ hostvars["node01"]["netconfig"]["cvlan"]["ipv4_address"] }}    node01
      {{ hostvars["node02"]["netconfig"]["cvlan"]["ipv4_address"] }}    node02
      {{ hostvars["node03"]["netconfig"]["cvlan"]["ipv4_address"] }}    node03
      {{ hostvars["node04"]["netconfig"]["cvlan"]["ipv4_address"] }}    node04
      {{ hostvars["node01"]["netconfig"]["cvlan"]["pod_ipv4_address"] }}    lc01
      {{ hostvars["node02"]["netconfig"]["cvlan"]["pod_ipv4_address"] }}    lc02
      {{ hostvars["node03"]["netconfig"]["cvlan"]["pod_ipv4_address"] }}    lc03
      {{ hostvars["node04"]["netconfig"]["cvlan"]["pod_ipv4_address"] }}    lc04
    marker: "# {mark} ANSIBLE MANAGED BLOCK clusterhosts"
