---
- name: restart slurmd
  service: name=slurmd state=restarted
  when: "'cluster_compute' in group_names"

- name: restart slurmctld
  service: name=slurmctld state=restarted
  when: "'cluster_head' in group_names"

- name: restart munge
  service: name=munge state=restarted
