---
- name: restart slurmd
  service: name=slurmd state=restarted
  when: "'compute' in group_names"

- name: restart slurmctld
  service: name=slurmctld state=restarted
  when: "'head' in group_names"

- name: restart munge
  service: name=munge state=restarted
