---
# (see nextcloud notes)
# ~~yum install dnsmasq~~
# ~~systemctl enable dnsmasq~~
# ~~systemctl start dnsmasq~~
# ~~update /etc/dnsmasq.conf~~
# yum install syslinux  # for /usr/share/syslinux/pxelinux.0
# ~~mkdir -p /tftpboot/pxelinux/files~~
# cp /usr/share/syslinux/pxelinux.0 /tftpboot/pxelinux/files/
# disable selinux (breaks /tftpboot access)
#   - setenforce 0
#   - Edit the /etc/selinux/config file to set the  SELINUX parameter to  disabled,
# mkdir /tftpboot/pxelinux/files/pxelinux.cfg/
# Fix up /tftpboot/pxelinux/files/pxelinux.cfg/default
# cp /boot/vmlinuz-3.10.0-957.1.3.el7.x86_64 /tftpboot/pxelinux/files/
# yum install dracut-network
# dracut -a "nfs network base" -f initrd.img
# populate /etc/exports
# systemctl start nfs
# add a root password to image
# disable selinux in image


- name: "dnsmasq package"
  yum:
    name: "dnsmasq"
    state: "present"
    
# Install syslinux so we can get /usr/share/syslinux/pxelinux.0
- name: "syslinux package"
  yum:
    name: "syslinux"
    state: "installed"

- name: "dnsmasq service"
  service: 
    name: "dnsmasq"
    state: "started"
    enabled: "yes"

- name: "dnsmasq config file"
  copy: 
    src: "dnsmasq.conf"
    dest: "/etc/dnsmasq.conf"

- name: "tftp directory"
  file:
    state: "directory"
    path: "/tftpboot/pxelinux/files/pxelinux.cfg"
    owner: "nobody"
    group: "nobody"
    
- name: "pxelinux.0 file"
  copy:
    src: "/usr/share/syslinux/pxelinux.0"
    dest: "/tftpboot/pxelinux/files/"
    owner: "nobody"
    group: "nobody"