- name: "Install NFS packages"
  dnf:
    name: nfs-utils
    state: present

- name: home mount
  ansible.posix.mount:
    name: /home/vagrant
    src: head:/home/vagrant
    fstype: nfs4
    state: mounted

# - name: seboolean nfs home dirs
#   seboolean:
#     name: use_nfs_home_dirs
#     state: yes
#     persistent: yes
