- name: "Install NFS packages"
  dnf:
    name: nfs-utils
    state: present

- name: "Mount home directories"
  ansible.posix.mount:
    name: /home/vagrant
    src: head:/home/vagrant
    fstype: nfs4
    state: mounted

# - name: "Set seboolean config on nfs home dirs"
#   seboolean:
#     name: use_nfs_home_dirs
#     state: yes
#     persistent: yes
