---
- name: "Install exports file"
  copy:
    src: etc/exports
    dest: /etc/exports
  notify:
   - restart nfs

- name: "Enable nfs service"
  service:
    name: nfs-server
    state: started
    enabled: yes
