netconfig:
  cvlan:
    conn_name: '{{ global_netconfig["cvlan"]["conn_name"] }}'
    device: '{{ global_netconfig["cvlan"]["device"] }}'
    ipv4_address: '{{ global_netconfig["cvlan"]["network"] | ansible.utils.nthhost(2) }}'

cluster_image_directory: "/images"
